import turtle
t = turtle.Turtle()
w = turtle.Screen()
p = turtle.Pen()
t.color('blue')
w.bgcolor('orange')
p.color('red')
p.shape('turtle')
p.pensize(5)
p.up()
p.left(90)
p.forward(50)
p.left(90)
p.forward(200)
p.left(180)
p.down()
p.fillcolor('red')
p.begin_fill()
for i in range(5):
    p.forward(400)
    p.right(144)
p.end_fill()
turtle.done()
