import turtle
t = turtle.Turtle()
w = turtle.Screen()
p = turtle.Pen()
t.color('red')
w.bgcolor('red')
p.pencolor('yellow')
p.pensize(3)
p.up()
p.left(90)
p.forward(200)
p.left(90)
p.forward(300)
p.down()
p.left(180)
p.fillcolor('yellow')
p.begin_fill()
for i in range(5):
    p.forward(200)
    p.right(144)
p.end_fill()
p.up()
p.forward(160)
p.left(90)
p.fd(100)
p.left(90)
for i in range(4):
    p.circle(200, -30)
    p.right(15)
    p.down()
    p.begin_fill()
    for j in range(5):
        p.fd(70)
        p.right(144)
    p.end_fill()
    p.up()
p.down()
turtle.done()
